### PR TITLE
submitting v2.0.0 because one of the target dependencies has updated …

### PR DESCRIPTION
**Pull request by rgrover**
…its major version

@marcuschangarm @0xc0170

### CODE REVIEW

**Comment by marcuschangarm** [comment]
Since you brought it up, I think https://github.com/rgrover/mbed-hal-nordic/blob/master/module.json#L19 should be moved to mbed-hal-nrf51822-mcu and the ```*``` changed to ```^1.whatissupported.com```.

**Comment by rgrover** [comment]
@marcuschangarm @0xc0170

**Comment by marcuschangarm** [comment]
+1

**Comment by rgrover** [comment]
@marcuschangarm: do you think this requires a jump in the major?

**Comment by 0xc0170** [comment]
I would say yes

**Pull request merged**
